### ISSUE TITLE
提示参数错误

### ISSUE THREAD

**Issue by yolo2013** [birdplane9527/node-xauth-fanfou#1]
执行get的post请求，options：{"url":"http://api.fanfou.com/statuses/user_timeline","oauth_token":"xxx","oauth_token_secret":"xxx","parameters":{"id":"xxx","page":1}}

**Comment by yolo2013** [comment]
不是很清楚，是我的token信息错误，还是传过去的参数错误

**Comment by yolo2013** [comment]
"{\"request\":\"\\/statuses\\/user_timeline.json\",\"error\":\"Invalid signature. Expected basestring is GET&http%3A%2F%2Fapi.fanfou.com%2Fstatuses%2Fuser_timeline.json&oauth_consumer_key%3D328980c258d8c5787c6a75ef243bd7ec%26oauth_nonce%3D6OGF5zCbFy6FVUxXqcMliksukW2QJMtI%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1497508578%26oauth_token%3D1449886-0daaa58cdcaa645051dfd3f4b6151e46%26oauth_version%3D1.0\"}"

**Comment by birdplane9527** [comment]
获取到Access Token了么？

**Comment by yolo2013** [comment]
@birdplane9527 可以了，重新做了些封装。

**Comment by yolo2013** [comment]
有一个问题想请教，我看饭否提供的API当中，发送消息没有看到图片的内容，请问发送的时候如何带图发送呢？
