### ISSUE TITLE
测试发送图片存在问题

### ISSUE THREAD

**Issue by yolo2013** [birdplane9527/node-xauth-fanfou#2]
似乎是文件流没有传到饭否的接口中去，在oauth的参数封装部分给整没了，不知道你是怎么处理的呢？

**Comment by birdplane9527** [comment]
这个不支持图片上传。我后来又重新写了个后台，发送图片的接口要单独处理，参数和图片的formdata一起传到后台。

**Comment by yolo2013** [comment]
嗯，我已经自己写了这部分的内容。
